name: shop_flutter
description: "E-commerce MVVM avec go_router et Provider"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^14.6.2

  # State Management - MVVM Pattern
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2

  # HTTP & API
  http: ^1.2.2

  # Local Storage
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2

  # Utilities
  equatable: ^2.0.7
  uuid: ^4.5.1
  intl: ^0.19.0

  # Platform specific
  share_plus: ^10.1.3
  url_launcher: ^6.3.1

  # Images
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/data/products.json
    - assets/images/
